### ISSUE TITLE
Extract: ensure all obs categoricals include all categories in the full dataset

### ISSUE THREAD

**Issue by sjfleming** [cellarium-ai/cellarium-cloud#153]
Fix the problem discussed here: https://github.com/cellarium-ai/cellarium-ml/issues/161

The problem is that `obs` categoricals like "dataset_id" do not have the same categories in each h5ad shard of extracted data.

- For cell type this seems to be handled here: https://github.com/cellarium-ai/cellarium-cloud/blob/99cc59ff5579b3167210ba574d297506b32e8087/src/casp/services/bq_ops/prepare_extract/main.py#L71-L72
- Basically we want to do this for every `obs` column (if it's categorical)
    - You probably don't have to make a separate file for each one, you could make one file with all the obs columns
- Use the information here https://github.com/cellarium-ai/cellarium-cloud/blob/99cc59ff5579b3167210ba574d297506b32e8087/src/casp/bq_scripts/extract_minibatch_to_anndata.py#L280-L282 like cell type did here https://github.com/cellarium-ai/cellarium-cloud/blob/99cc59ff5579b3167210ba574d297506b32e8087/src/casp/bq_scripts/extract_minibatch_to_anndata.py#L263-L270

**Comment by fedorgrab** [comment]
This was fixed during this [PR](https://github.com/cellarium-ai/cellarium-cloud/pull/195)

To be more specific, this fix got lost in [this commit](https://github.com/cellarium-ai/cellarium-cloud/pull/195/commits/0a84111b19f28919d9700138c66704c42aa7e2f4)
