### ISSUE TITLE
Add "index" column to gene allow list table

### ISSUE THREAD

**Issue by kcibul** [cellarium-ai/cellarium-cloud#30]
Currently this is modeled as a set, but it should be an ordered list.  

Add a new column, populate with values (based on lexical ordering)

dsp-cell-annotation-service.cas_reference_data.refdata-gex-GRCh38-2020-A

**Comment by fedorgrab** [comment]
It was done during [June release PR](https://github.com/cellarium-ai/cellarium-cloud/pull/85)
