### ISSUE TITLE
Convention for tensor names and assert statements

### ISSUE THREAD

**Issue by mbabadi** [cellarium-ai/cellarium-cloud#45]
It is extremely helpful to stick to a uniform naming convention for all the tensors.  Since Python is dynamically typed, it is impossible to infer the dimensions of a given tensor and tensor type hints are uninformative as they stand currently.

Consider the following function:

```
def forward(tensor1: torch.Tensor, tensor2: torch.Tensor) -> torch.Tensor:
    new_tensor1 = torch.log1p(tensor1)
    new_tensor2 = new_tensor1 + tensor2.unsqueeze(-1)
    return new_tensor2
```

By inspecting this code, it takes a good while to understand that `tensor2` _probably_ one fewer dimensions that `tensor1`, and that the leftmost dimensions of `tensor1` and `tensor2` must match; or _perhaps_ `tensor2` is a scalar? My point is, the combination of PyTorch's extremely helpful [broadcasting semantics](https://pytorch.org/docs/stable/notes/broadcasting.html) and dynamic typing is recipe for unreadable code.

Now, consider the following alternative code:

```
def forward(raw_counts_ng: torch.Tensor, bias_n: torch.Tensor) -> torch.Tensor:
    """some description:
    :param raw_counts_ng: a 2d tensor with shape (n_cells, n_genes)
    :param bias_n: a 1d tensor with shape (n_cells,)
    """
    assert raw_counts_ng.ndim == 2
    assert bias_n.ndim == 1
    assert raw_counts_ng.shape[0] == bias_n.shape[0]

    log1p_counts_ng = torch.log1p(raw_counts_ng)
    biased_log1p_counts_ng = log1p_counts_ng + bias_n.unsqueeze(-1)
    return biased_log1p_counts_ng 
```
We have suffixed our tensor names via a certain convention, e.g. we have used `n` for cell index and `g` for gene index, so that the reader would know the tensor `raw_counts_ng` is 2d, the leftmost dimension denotes the cell index, and the rightmost dimension denotes the gene index. The assert statements makes this very clear too.

- [ ] Let us make sure we stick to such a naming convention going forward: every tensor variable should be named like `<name>_<indices>` where `<name>` is arbitrary and `<indices>` is a list of alphabets signifying different tensor dimensions. For example, `my_tensor_n1g` is a 3d tensor with shape `(n_cells, 1, n_genes)`; or `my_tensor_nk` could be a 2d tensor with shape `(n_cells, n_latents)` where we have hopefully used the letter `k` to consistently refer to as the latent dimension.
- [ ] Let us use assert statements as much as possible. The assert statements a extremely cheap, yet, they catch errors that are otherwise _notoriously_ difficult to catch. 
- [ ] Let us go through the code we have written so far and implement these conventions.

**Comment by mbabadi** [comment]
@fedorgrab @kcibul Where would be a good place to document our coding conventions? Shall we start a separate markdown for that?

**Comment by ordabayevy** [comment]
What would be the naming convention for subsampling?

```
# x_ng -> data with n cells and g genes
with plate("cells", ...) as idx:
    x_?g = x_ng[idx]
```

**Comment by fedorgrab** [comment]
This issue is no longer needed as there's cellarium-ml library.
