### ISSUE TITLE
Lazy AnnData class

### ISSUE THREAD

**Issue by ordabayevy** [cellarium-ai/cellarium-cloud#48]
One possible approach to working with a large number of `AnnData` files is to create a `LazyAnnData`. It would have a `__getitem__` method that loads one file at a time into a memory and fetches the cell at the given index from it. To make the dataloader efficient we need a custom `Sampler` that makes sure that all indices from the already loaded file are exhausted before moving on to another file. Also this sampler needs to make sure that different files are loaded to multiple nodes.

TODO LIST

- [ ] #49 
- [ ] Lazy AnnData class with the `__getitem__` method
- [ ] Custom sampler that will handle all the fancy logic

**Comment by fedorgrab** [comment]
This issue is not relevant anymore as [Cellarium ML](https://github.com/cellarium-ai/cellarium-ml) repository was created.
